# Generated by Django 4.0.3 on 2022-05-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='office_id',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
