# Generated by Django 4.0.3 on 2022-05-25 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0006_alter_district_state_alter_division_office_id_and_more'),
        ('accounts', '0002_rename_designation_id_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='configuration.designation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to='configuration.office'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
