# Generated by Django 3.2.13 on 2022-05-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line1', models.CharField(max_length=128)),
                ('address_line2', models.CharField(blank=True, default='', max_length=128)),
                ('address_line3', models.CharField(blank=True, default='', max_length=128)),
                ('pin', models.CharField(max_length=6)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.district')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.state')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.office')),
            ],
        ),
    ]
