# Generated by Django 4.0.3 on 2022-05-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_district_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='state_id',
            new_name='state',
        ),
    ]
