# Generated by Django 4.0.3 on 2022-05-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_rename_state_id_district_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('contact_no', models.CharField(max_length=15)),
                ('gst_no', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='office',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='state_id',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.state'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.office')),
                ('parents_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.location')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.itemtype')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuration.body'),
            preserve_default=False,
        ),
    ]
