# Generated by Django 4.0.3 on 2022-05-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_accounthead_body_itemtype_unit_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.state'),
        ),
        migrations.AlterField(
            model_name='division',
            name='office_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.office'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.itemtype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.office'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parents_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.location'),
        ),
        migrations.AlterField(
            model_name='office',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.body'),
        ),
        migrations.AlterField(
            model_name='office',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.district'),
        ),
        migrations.AlterField(
            model_name='office',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.state'),
        ),
    ]
