# Generated by Django 4.0.3 on 2022-06-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_district_state_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_body', to='configuration.body'),
        ),
        migrations.AlterField(
            model_name='office',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_district', to='configuration.district'),
        ),
        migrations.AlterField(
            model_name='office',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_state', to='configuration.state'),
        ),
    ]
