# Generated by Django 4.0.3 on 2022-06-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_alter_office_body_alter_office_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='office_id',
            new_name='office',
        ),
    ]
