# Generated by Django 4.0.3 on 2022-06-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_rename_office_id_division_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='body',
        ),
    ]
