# Generated by Django 4.0.3 on 2022-06-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_itemallocation_body_and_more'),
        ('configuration', '0012_remove_office_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
    ]
