# Generated by Django 4.0.3 on 2022-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_delete_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='remarks',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_no',
            field=models.CharField(max_length=15),
        ),
    ]
