# Generated by Django 4.0.3 on 2022-05-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0006_alter_district_state_alter_division_office_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=12)),
                ('purpose', models.CharField(max_length=512)),
                ('cheque_date', models.DateField()),
                ('date_of_receipt', models.DateField(auto_now=True)),
                ('document_url', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.accounthead')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDispatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=2048)),
                ('subject', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('dispatch_on', models.DateField()),
                ('received_on', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_dispatch_created_by', to=settings.AUTH_USER_MODEL)),
                ('dispatch_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_dispatch', to=settings.AUTH_USER_MODEL)),
                ('dispatch_from_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_from_body', to='configuration.body')),
                ('dispatch_to_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_to_body', to='configuration.body')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_received_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_dispatch_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=128)),
                ('order_no', models.CharField(blank=True, max_length=128)),
                ('invoice_no', models.CharField(blank=True, max_length=128)),
                ('purchase_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_created_by', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.fund')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItemReceivedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(default=0)),
                ('received_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchasedetails')),
                ('received_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.body')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_specification', models.CharField(blank=True, max_length=1024)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchasedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReceivedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_serial_no', models.CharField(max_length=128)),
                ('item_specification', models.CharField(blank=True, max_length=1024)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('warranty_period', models.SmallIntegerField(default=0)),
                ('is_item_in_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_received_created_by', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemdispatchdetail')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_received_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDispatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispatch', models.IntegerField(default=0)),
                ('dispatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemdispatchdetail')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.item')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchasedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.body')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_allocation_created_by', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.location')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_allocation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
