# Generated by Django 4.0.3 on 2022-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
