# Generated by Django 4.0.3 on 2022-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fund_cheque_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
