# Generated by Django 4.0.3 on 2022-05-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_district_state_alter_division_office_id_and_more'),
        ('inventory', '0003_alter_fund_cheque_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='account_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_head', to='configuration.accounthead'),
        ),
    ]
