# Generated by Django 4.0.3 on 2022-05-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_fund_account_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemallocation',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemreceiveddetails'),
            preserve_default=False,
        ),
    ]
