# Generated by Django 4.0.3 on 2022-05-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemallocation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='cheque_no',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='itemallocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_item', to='inventory.itemreceiveddetails'),
        ),
    ]
