# Generated by Django 4.0.3 on 2022-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_fund_cheque_no_alter_itemallocation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='document_url',
            field=models.ImageField(upload_to='cheque'),
        ),
    ]
