# Generated by Django 4.0.3 on 2022-06-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_remove_office_body'),
        ('inventory', '0007_alter_fund_document_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemallocation',
            name='body',
        ),
        migrations.RemoveField(
            model_name='itemdispatchdetail',
            name='dispatch_from_body',
        ),
        migrations.RemoveField(
            model_name='itemdispatchdetail',
            name='dispatch_to_body',
        ),
        migrations.RemoveField(
            model_name='purchaseitemreceiveddetails',
            name='received_body',
        ),
        migrations.AddField(
            model_name='itemallocation',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.office'),
        ),
        migrations.AddField(
            model_name='purchaseitemreceiveddetails',
            name='received_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.office'),
        ),
    ]
