# Generated by Django 4.0.3 on 2022-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_itemallocation_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='document_url',
            field=models.FileField(upload_to='cheque'),
        ),
    ]
