# Generated by Django 4.0.3 on 2022-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_fund_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitemlist',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
