# Generated by Django 4.0.3 on 2022-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchaseitemlist_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitemreceiveddetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
