# Generated by Django 4.0.3 on 2022-06-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_vendor_bank_account_no_vendor_description_and_more'),
        ('inventory', '0012_purchaseitemreceiveddetails_remarks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseitemreceiveddetails',
            unique_together={('purchase', 'item')},
        ),
    ]
