# Generated by Django 4.0.3 on 2022-06-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_purchaseitemreceiveddetails_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseitemreceiveddetails',
            unique_together=set(),
        ),
    ]
