# Generated by Django 4.0.3 on 2022-06-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_vendor_bank_account_no_vendor_description_and_more'),
        ('inventory', '0014_alter_purchaseitemreceiveddetails_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdispatchdetail',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='itemdispatchdetail',
            name='received_on',
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='to_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.office'),
        ),
    ]
