# Generated by Django 4.0.3 on 2022-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_itemdispatchdetail_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
