# Generated by Django 4.0.3 on 2022-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_itemdispatchdetail_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchlist',
            name='remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
