# Generated by Django 4.0.3 on 2022-06-21 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0017_itemdispatchlist_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='received_on',
            field=models.DateField(blank=True, default='2022-06-06'),
            preserve_default=False,
        ),
    ]
