# Generated by Django 4.0.3 on 2022-06-21 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_vendor_bank_account_no_vendor_description_and_more'),
        ('inventory', '0018_itemdispatchdetail_is_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledgge_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledgge_remarks',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledgge_subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledgge_to_address',
            field=models.CharField(default='Na', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledgge_to_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgge_to_office', to='configuration.office'),
        ),
    ]
