# Generated by Django 4.0.3 on 2022-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_itemdispatchdetail_acknowledgge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='acknowledgge_description',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='acknowledgge_subject',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='acknowledgge_to_address',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
