# Generated by Django 4.0.3 on 2022-06-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_itemdispatchdetail_acknowledgge_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='acknowledgge_description',
            new_name='acknowledge_description',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='acknowledgge_remarks',
            new_name='acknowledge_remarks',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='acknowledgge_subject',
            new_name='acknowledge_subject',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='acknowledgge_to_address',
            new_name='acknowledge_to_address',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='acknowledgge_to_office',
            new_name='acknowledge_to_office',
        ),
    ]
