# Generated by Django 4.0.3 on 2022-06-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_vendor_bank_account_no_vendor_description_and_more'),
        ('inventory', '0022_rename_acknowledgge_description_itemdispatchdetail_acknowledge_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='description',
            new_name='dispatch_description',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='remarks',
            new_name='dispatch_remarks',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='subject',
            new_name='dispatch_subject',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='to_address',
            new_name='dispatch_to_address',
        ),
        migrations.RenameField(
            model_name='itemdispatchdetail',
            old_name='to_office',
            new_name='dispatch_to_office',
        ),
        migrations.RemoveField(
            model_name='itemdispatchdetail',
            name='acknowledge_to_office',
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='dispatch_from_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_from_office', to='configuration.office'),
        ),
    ]
