# Generated by Django 4.0.3 on 2022-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_description_itemdispatchdetail_dispatch_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='received_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
