# Generated by Django 4.0.3 on 2022-06-22 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_vendor_bank_account_no_vendor_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0024_alter_itemdispatchdetail_received_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemReceivedDetails',
            new_name='DispatchItemReceivedDetails',
        ),
    ]
