# Generated by Django 4.0.3 on 2022-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rename_itemreceiveddetails_dispatchitemreceiveddetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='is_item_in_use',
            new_name='is_in_use',
        ),
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='item_serial_no',
            new_name='serial_no',
        ),
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='item_specification',
            new_name='specification',
        ),
        migrations.AddField(
            model_name='dispatchitemreceiveddetails',
            name='model_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
