# Generated by Django 4.0.3 on 2022-06-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_is_item_in_use_dispatchitemreceiveddetails_is_in_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitemreceiveddetails',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchasedetails'),
        ),
    ]
