# Generated by Django 4.0.3 on 2022-06-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_dispatchitemreceiveddetails_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchitemreceiveddetails',
            name='purchase',
        ),
        migrations.AddField(
            model_name='dispatchitemreceiveddetails',
            name='item_dispatch_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemdispatchlist'),
        ),
    ]
