# Generated by Django 4.0.3 on 2022-07-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_dispatchitemreceiveddetails_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitemreceiveddetails',
            name='purchase_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseitemlist'),
            preserve_default=False,
        ),
    ]
