# Generated by Django 4.0.3 on 2022-07-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_purchaseitemreceiveddetails_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchasedetails'),
        ),
        migrations.AlterField(
            model_name='purchaseitemreceiveddetails',
            name='purchase_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_item', to='inventory.purchaseitemlist'),
        ),
    ]
