# Generated by Django 4.0.3 on 2022-07-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_purchasedetails_is_dispatchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetails',
            name='purchase_order_url',
            field=models.FileField(default=' ', upload_to='purchase_order'),
            preserve_default=False,
        ),
    ]
