# Generated by Django 4.0.3 on 2022-07-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_purchasedetails_purchase_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledge_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='handover_doc_url',
            field=models.FileField(default='', upload_to='hand_over_document'),
            preserve_default=False,
        ),
    ]
