# Generated by Django 4.0.3 on 2022-07-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_itemdispatchdetail_acknowledge_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchdetail',
            name='acknowledge_doc_url',
            field=models.FileField(default='', upload_to='acknowledge_document'),
            preserve_default=False,
        ),
    ]
