# Generated by Django 4.0.3 on 2022-07-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_itemdispatchdetail_acknowledge_doc_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='item_dispatch_list',
            new_name='purchase',
        ),
        migrations.AddField(
            model_name='itemdispatchlist',
            name='purchase_item',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_item', to='inventory.purchaseitemlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='acknowledge_doc_url',
            field=models.FileField(blank=True, null=True, upload_to='acknowledge_document'),
        ),
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='handover_doc_url',
            field=models.FileField(blank=True, null=True, upload_to='hand_over_document'),
        ),
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='received_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
