# Generated by Django 4.0.3 on 2022-07-05 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0037_rename_item_dispatch_list_dispatchitemreceiveddetails_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='dispatch_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdispatchlist',
            name='purchase_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_item', to='inventory.purchaseitemreceiveddetails'),
        ),
    ]
