# Generated by Django 4.0.3 on 2022-07-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_itemdispatchdetail_dispatch_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdispatchlist',
            old_name='purchase_item',
            new_name='purchase_item_received',
        ),
    ]
