# Generated by Django 4.0.3 on 2022-07-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_dispatchitemreceiveddetails_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchitemreceiveddetails',
            name='test',
        ),
    ]
