# Generated by Django 4.0.3 on 2022-07-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_remove_dispatchitemreceiveddetails_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitemreceiveddetails',
            name='dispathce_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemdispatchlist'),
        ),
    ]
