# Generated by Django 4.0.3 on 2022-07-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_rename_dispathce_list_id_dispatchitemreceiveddetails_dispatch_list_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='dispatch_list_id',
            new_name='dispatch_list',
        ),
    ]
