# Generated by Django 4.0.3 on 2022-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_rename_dispatch_list_id_dispatchitemreceiveddetails_dispatch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchitemreceiveddetails',
            old_name='dispatch_list',
            new_name='item_dispatch_list',
        ),
    ]
