# Generated by Django 4.0.3 on 2022-07-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_rename_dispatch_list_dispatchitemreceiveddetails_item_dispatch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdispatchdetail',
            name='acknowledge_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
