# Generated by Django 4.0.3 on 2022-08-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_fund_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispatchlist',
            name='lot_no',
            field=models.TextField(default='NA', max_length=25),
        ),
    ]
